# Generated by Django 4.2.2 on 2023-07-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='castMap',
            fields=[
                ('castID', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'castMap',
            },
        ),
        migrations.CreateModel(
            name='titleGenres',
            fields=[
                ('genreID', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'titleGenres',
            },
        ),
        migrations.CreateModel(
            name='titleInfo',
            fields=[
                ('titleID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('yearReleased', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'titleInfo',
            },
        ),
        migrations.CreateModel(
            name='titleCasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.castmap')),
                ('titleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.titleinfo')),
            ],
            options={
                'db_table': 'titleCasts',
            },
        ),
        migrations.CreateModel(
            name='genreMap',
            fields=[
                ('mappingID', models.AutoField(primary_key=True, serialize=False)),
                ('genreID', models.ForeignKey(db_column='genreID', on_delete=django.db.models.deletion.CASCADE, to='home.titlegenres')),
                ('titleID', models.ForeignKey(db_column='titleID', on_delete=django.db.models.deletion.CASCADE, to='home.titleinfo')),
            ],
            options={
                'db_table': 'genreMap',
            },
        ),
    ]
